const User = require('../models/User');
// const seed = require('./user-seed-data').USERS;
const mongoose = require('mongoose');
const db = require('../config/keys').mongoURI;

const USERS = [
  new User({
  name: 'Akram',
  email: 'user1@pmp.com',
  password: 'password',
  birthday: '1980/01/01',
  state: 'CA',
  zip: '94043',
  orientation:
  {
    Straight: true,
    Gay: false,
    Bisexual: false,
    Lesbian: false,
    Queer: false,
    Pansexual: false,
    Questioning: false,
    Heteroflexible: false,
    Homoflexible: false,
    Asexual: false,
    'Gray-asexual': false,
    Demisexual: false,
    Reciprosexual: false,
    Akiosexual: false,
    Aceflux: false,
    Grayromantic: false,
    Demiromantic: false,
    Recipromantic: false,
    Akioromantic: false,
    Aroflux: false
  },
  gender:
  {
    Woman: false,
    Man: true,
    Agender: false,
    Androgynous: false,
    Bigender: false,
    'Cis Man': true,
    'Cis Woman': false,
    Genderfluid: false,
    Genderqueer: false,
    'Gender Nonconforming': false,
    Hijira: false,
    Intersex: false,
    'Non-binary': false,
    Other: false,
    Pangender: false,
    Transfeminine: false,
    Transgender: false,
    Transmasculine: false,
    Transsexual: false,
    'Trans Man': false,
    'Trans Woman': false,
    'Two Spirit': false
  },
  relationship_status: 'Single',
  relationship_type: 'Monogamous',
  pronouns: ':) / (:',
  height: '5\'-7"',
  body_type: 'Thin',
  ethnicity:
  {
    Asian: false,
    Black: false,
    'Hispanic / Latin': false,
    Indian: false,
    'Middle Eastern': false,
    'Native American': false,
    'Pacific Islander': false,
    White: false,
    Other: false
  },
  languages: 'C++',
  fluency: '',
  politics: '',
  education: '',
  occupation: 'Monogamous',
  employer: 'Monogamous',
  religion: 'Agnostic',
  religion_weight: '(but it\'s not important)',
  sign: '',
  smoking: '',
  drinks: '',
  marijuana: '',
  diet: 'Kosher',
  children: '',
  wants_children: 'Might want kids',
  pets:
  {
    'Has dog(s)': true,
    'Has cat(s)': false,
    'Has other pet(s)': false,
    'Doesn\'t have pet(s)': false
  },
  gamelist: [],
  game_genres: [],
  platforms: [],
  pref_orientation:
  {
    Straight: false,
    Gay: false,
    Bisexual: false,
    Lesbian: false,
    Queer: false,
    Pansexual: false,
    Questioning: false,
    Heteroflexible: false,
    Homoflexible: false,
    Asexual: false,
    'Gray-asexual': false,
    Demisexual: false,
    Reciprosexual: false,
    Akiosexual: false,
    Aceflux: false,
    Grayromantic: false,
    Demiromantic: false,
    Recipromantic: false,
    Akioromantic: false,
    Aroflux: false
  },
  pref_gender:
  {
    Woman: false,
    Man: false,
    Agender: false,
    Androgynous: false,
    Bigender: false,
    'Cis Man': false,
    'Cis Woman': false,
    Genderfluid: false,
    Genderqueer: false,
    'Gender Nonconforming': false,
    Hijira: false,
    Intersex: false,
    'Non-binary': false,
    Other: false,
    Pangender: false,
    Transfeminine: false,
    Transgender: false,
    Transmasculine: false,
    Transsexual: false,
    'Trans Man': false,
    'Trans Woman': false,
    'Two Spirit': false
  },
  pref_distance: 'replace',
  pref_age: 'replace',
  pref_connections:
  {
    'New friends': false,
    'Long-term dating': false,
    'Short-term dating': false,
    Hookups: false
  },
  pref_height: 'replace',
  profile_essay_questions:
    ['My self-summary',
      'Current goal',
      'I could probably beat you at',
      'My golden rule',
      'I value',
      'The last show I binged',
      'A perfect day',
      'The most private thing I\'m willing to admit',
      'What I\'m actually looking for'],
  profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
  liked: [],
  passed: [],
  blocked: []
}),
  new User({
    name: 'Izabelle',
    email: 'user2@pmp.com',
    password: 'password',
    birthday: '1986/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: true,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: true,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: '',
    height: '5\'-4"',
    body_type: 'Curvy',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: true,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': true,
      White: false,
      Other: false
    },
    languages: 'English',
    fluency: 'Somewhat',
    politics: '',
    education: 'Undergraduate degree',
    occupation: '',
    employer: '',
    religion: '',
    religion_weight: '',
    sign: '',
    smoking: '',
    drinks: '',
    marijuana: 'Often',
    diet: '',
    children: '',
    wants_children: '',
    pets:
    {
      'Has dog(s)': false,
      'Has cat(s)': false,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Martine',
    email: 'user3@pmp.com',
    password: 'password',
    birthday: '1998/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: false,
      Gay: true,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: true,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: 'they/them',
    height: '',
    body_type: '',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: '',
    education: '',
    occupation: '',
    employer: '',
    religion: '',
    religion_weight: '',
    sign: '',
    smoking: '',
    drinks: 'Often',
    marijuana: '',
    diet: '',
    children: '',
    wants_children: '',
    pets:
    {
      'Has dog(s)': false,
      'Has cat(s)': false,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Edgar',
    email: 'user4@pmp.com',
    password: 'password',
    birthday: '1996/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: true,
      Questioning: true,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: true,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: true,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: 'he/his',
    height: '',
    body_type: '',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: 'Politically liberal',
    education: '',
    occupation: 'Monogamous',
    employer: 'Monogamous',
    religion: '',
    religion_weight: '',
    sign: 'Leo',
    smoking: '',
    drinks: '',
    marijuana: 'Sometimes',
    diet: 'Intermittent Fasting',
    children: '',
    wants_children: '',
    pets:
    {
      'Has dog(s)': true,
      'Has cat(s)': false,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Elsie-May',
    email: 'user5@pmp.com',
    password: 'password',
    birthday: '1995/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: true,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: '',
    height: '5\'-5"',
    body_type: 'Overweight',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: 'Politically moderate',
    education: 'Trade/tech school',
    occupation: 'Monogamous',
    employer: 'Monogamous',
    religion: '',
    religion_weight: '',
    sign: 'Sagittarius',
    smoking: '',
    drinks: '',
    marijuana: '',
    diet: 'Lactovegetarian',
    children: 'Has kid(s)',
    wants_children: 'and doesn\'t want more',
    pets:
    {
      'Has dog(s)': false,
      'Has cat(s)': false,
      'Has other pet(s)': true,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Braydon',
    email: 'user6@pmp.com',
    password: 'password',
    birthday: '1983/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: true,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: '',
    height: '',
    body_type: '',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: '',
    education: 'Graduate degree',
    occupation: '',
    employer: '',
    religion: '',
    religion_weight: '',
    sign: 'Aries',
    smoking: '',
    drinks: 'Sometimes',
    marijuana: '',
    diet: 'Omnivore',
    children: '',
    wants_children: '',
    pets:
    {
      'Has dog(s)': false,
      'Has cat(s)': false,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Mason',
    email: 'user7@pmp.com',
    password: 'password',
    birthday: '1992/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: 'she/her',
    height: '',
    body_type: '',
    ethnicity:
    {
      Asian: true,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: 'English',
    fluency: '',
    politics: 'Politically liberal',
    education: '',
    occupation: 'Monogamous',
    employer: 'Monogamous',
    religion: '',
    religion_weight: '',
    sign: '',
    smoking: 'Never',
    drinks: '',
    marijuana: 'Never',
    diet: 'Halal',
    children: '',
    wants_children: '',
    pets:
    {
      'Has dog(s)': false,
      'Has cat(s)': false,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Nicholas',
    email: 'user8@pmp.com',
    password: 'password',
    birthday: '1969/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: true,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: '',
    height: '',
    body_type: '',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: '',
    education: 'Undergraduate degree',
    occupation: '',
    employer: '',
    religion: '',
    religion_weight: '',
    sign: 'Libra',
    smoking: 'Often',
    drinks: '',
    marijuana: '',
    diet: '',
    children: 'Doesn\'t have kids',
    wants_children: '',
    pets:
    {
      'Has dog(s)': false,
      'Has cat(s)': true,
      'Has other pet(s)': true,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Tobias',
    email: 'user9@pmp.com',
    password: 'password',
    birthday: '1979/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: 'master',
    height: '',
    body_type: '',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: '',
    education: 'In college',
    occupation: '',
    employer: '',
    religion: 'Sikh',
    religion_weight: '',
    sign: 'Gemini',
    smoking: 'Never',
    drinks: '',
    marijuana: 'Sometimes',
    diet: 'Omnivore',
    children: 'Doesn\'t have kids',
    wants_children: '',
    pets:
    {
      'Has dog(s)': false,
      'Has cat(s)': false,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Kingsley',
    email: 'user10@pmp.com',
    password: 'password',
    birthday: '1988/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: false,
      Gay: true,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: '',
    height: '',
    body_type: '',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: 'Politically conservative',
    education: '',
    occupation: '',
    employer: '',
    religion: 'Christian',
    religion_weight: '',
    sign: '',
    smoking: '',
    drinks: '',
    marijuana: '',
    diet: '',
    children: 'Has kid(s)',
    wants_children: '',
    pets:
    {
      'Has dog(s)': false,
      'Has cat(s)': false,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Britany',
    email: 'user11@pmp.com',
    password: 'password',
    birthday: '1984/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: false,
      Gay: true,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: true,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: true,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: '',
    height: '6\'-0"',
    body_type: 'Fit',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: 'Other',
    education: '',
    occupation: '',
    employer: '',
    religion: '',
    religion_weight: '',
    sign: '',
    smoking: 'Sometimes',
    drinks: '',
    marijuana: '',
    diet: '',
    children: '',
    wants_children: '',
    pets:
    {
      'Has dog(s)': true,
      'Has cat(s)': true,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Gavin',
    email: 'user12@pmp.com',
    password: 'password',
    birthday: '2000/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: true,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': true
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: '',
    height: '5\'-10"',
    body_type: '',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: 'Politically liberal',
    education: 'In college',
    occupation: 'Monogamous',
    employer: 'Monogamous',
    religion: '',
    religion_weight: '',
    sign: '',
    smoking: '',
    drinks: 'Never',
    marijuana: 'Often',
    diet: '',
    children: '',
    wants_children: '',
    pets:
    {
      'Has dog(s)': true,
      'Has cat(s)': false,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Jacqueline',
    email: 'user13@pmp.com',
    password: 'password',
    birthday: '1997/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: '',
    height: '',
    body_type: '',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: 'Politically liberal',
    education: 'Undergraduate degree',
    occupation: '',
    employer: '',
    religion: 'Atheist',
    religion_weight: '',
    sign: '',
    smoking: '',
    drinks: 'Often',
    marijuana: '',
    diet: '',
    children: '',
    wants_children: '',
    pets:
    {
      'Has dog(s)': true,
      'Has cat(s)': false,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
  new User({
    name: 'Kamila',
    email: 'user14@pmp.com',
    password: 'password',
    birthday: '1993/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: false,
      Gay: true,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: true,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: '',
    height: '',
    body_type: '',
    ethnicity:
    {
      Asian: false,
      Black: true,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: '',
    education: 'Undergraduate degree',
    occupation: '',
    employer: '',
    religion: 'Jewish',
    religion_weight: '(and laughing about it)',
    sign: '',
    smoking: '',
    drinks: 'Often',
    marijuana: 'Often',
    diet: 'Vegan',
    children: 'Has kid(s)',
    wants_children: '',
    pets:
    {
      'Has dog(s)': false,
      'Has cat(s)': true,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  }),
    new User({
    name: 'Rebeca',
    email: 'user15@pmp.com',
    password: 'password',
    birthday: '1975/01/01',
    state: 'CA',
    zip: '94043',
    orientation:
    {
      Straight: true,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    relationship_status: 'Single',
    relationship_type: 'Monogamous',
    pronouns: '',
    height: '',
    body_type: 'Jacked',
    ethnicity:
    {
      Asian: false,
      Black: false,
      'Hispanic / Latin': false,
      Indian: false,
      'Middle Eastern': false,
      'Native American': false,
      'Pacific Islander': false,
      White: false,
      Other: false
    },
    languages: '',
    fluency: '',
    politics: '',
    education: 'Undergraduate degree',
    occupation: '',
    employer: '',
    religion: 'Muslim',
    religion_weight: '(and it\'s important)',
    sign: '',
    smoking: '',
    drinks: '',
    marijuana: '',
    diet: '',
    children: '',
    wants_children: '',
    pets:
    {
      'Has dog(s)': false,
      'Has cat(s)': false,
      'Has other pet(s)': false,
      'Doesn\'t have pet(s)': false
    },
    gamelist: [],
    game_genres: [],
    platforms: [],
    pref_orientation:
    {
      Straight: false,
      Gay: false,
      Bisexual: false,
      Lesbian: false,
      Queer: false,
      Pansexual: false,
      Questioning: false,
      Heteroflexible: false,
      Homoflexible: false,
      Asexual: false,
      'Gray-asexual': false,
      Demisexual: false,
      Reciprosexual: false,
      Akiosexual: false,
      Aceflux: false,
      Grayromantic: false,
      Demiromantic: false,
      Recipromantic: false,
      Akioromantic: false,
      Aroflux: false
    },
    pref_gender:
    {
      Woman: false,
      Man: false,
      Agender: false,
      Androgynous: false,
      Bigender: false,
      'Cis Man': false,
      'Cis Woman': false,
      Genderfluid: false,
      Genderqueer: false,
      'Gender Nonconforming': false,
      Hijira: false,
      Intersex: false,
      'Non-binary': false,
      Other: false,
      Pangender: false,
      Transfeminine: false,
      Transgender: false,
      Transmasculine: false,
      Transsexual: false,
      'Trans Man': false,
      'Trans Woman': false,
      'Two Spirit': false
    },
    pref_distance: 'replace',
    pref_age: 'replace',
    pref_connections:
    {
      'New friends': false,
      'Long-term dating': false,
      'Short-term dating': false,
      Hookups: false
    },
    pref_height: 'replace',
    profile_essay_questions:
      ['My self-summary',
        'Current goal',
        'I could probably beat you at',
        'My golden rule',
        'I value',
        'The last show I binged',
        'A perfect day',
        'The most private thing I\'m willing to admit',
        'What I\'m actually looking for'],
    profile_essay_answers: ['', '', '', '', '', '', '', '', ''],
    liked: [],
    passed: [],
    blocked: []
  })];

mongoose
  .connect(db, { useNewUrlParser: true })
  .then(() => console.log('Connected to MongoDB successfully'))
  .catch(err => console.log(err));

var done = 0;
for (let i = 0; i < USERS.length; i++){
  USERS[i].save((err, result) => {
    done++;
    if(done === USERS.length) exit();
  });
}

const exit = () => mongoose.disconnect();